externalSecret:
  registry: false

ingress:
  enabled: false
  hostname: "kafka-poc.ocp.cloudscale.puzzle.ch"

kafka-ui:
  deployment:
    replicas: 1
    image: provectuslabs/kafka-ui
    tag: latest
    imagePullPolicy: IfNotPresent
    imagePullSecrets: registry-pull-secret
    containerPort: 8080
    env:
      KAFKA_CLUSTER_NAME: mykafka-cluster
      KAFKA_BROKER: mykafka-cluster-kafka-bootstrap.kafka:9092
  service:
    enabled: true
    type: "ClusterIP"
    port: 8080

kafka-cluster:
  cluster:
    name: mykafka-cluster
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: false
      default.replication.factor: 1
      delete.topic.enable: true
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  nodePool:
    name: dual-role
    cluster: mykafka-cluster
    replicas: 1
    roles:
      - controller
      - broker
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        class: cloudscale-volume-ssd
        deleteClaim: true
        kraftMetadata: shared
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
  topics:
#    - name: topic-solar-data
#      cluster: mykafka-cluster
#      partitions: 1
#      replicas: 1
#      config:
#        retention.ms: 604800000
#        segment.bytes: 104857500
#        cleanup.policy: delete

#    - name: topic-traffic-data
#      cluster: mykafka-cluster
#      partitions: 1
#      replicas: 1
#      config:
#        retention.ms: 604800000
#        segment.bytes: 104857500
#        cleanup.policy: delete

#    - name: topic-weather-data
#      cluster: mykafka-cluster
#      partitions: 1
#      replicas: 1
#      config:
#        retention.ms: 604800000
#        segment.bytes: 104857500
#        cleanup.policy: delete