apiVersion: v2
name: solar-system
version: 1.0.0
dependencies:
  - name: mqtt-bridge
    version: 0.1.0
    repository: oci://harbor.puzzle.ch/pitc-cicd-private/kafka-poc/helm-charts
  - name: mqtt-producer
    version: 0.1.1
    repository: oci://harbor.puzzle.ch/pitc-cicd-private/kafka-poc/helm-charts
  - name: kafka-web-consumer
    version: 0.1.1
    repository: oci://harbor.puzzle.ch/pitc-cicd-private/kafka-poc/helm-charts