mqtt-bridge:
  image:
    repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc
    tag: mqtt-bridge-latest
    pullPolicy: IfNotPresent
  env:
    MQTT_BROKER: "tcp://traffic-system-mosquitto.traffic-system.svc.cluster.local:1883"
    MQTT_TOPIC: "traffic/data"
    KAFKA_BROKER: "mykafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
    KAFKA_TOPIC: "topic-traffic-data"
    KAFKA_BALANCER: "hash"

kafka-web-consumer:
  image:
  #  repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc traffic-kafka-web-consumer
    repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc traffic-consumer
    tag: latest
    pullPolicy: Always

  env:
    KAFKA_BROKER: "mykafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
    KAFKA_TOPIC: "topic-traffic-data"
    KAFKA_CONSUMER_GROUP: "gui-consumer"
    KAFKA_START_OFFSET: "first"

mqtt-producer:
  replicaCount: 1
  image:
    repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc
    tag: traffic-mqtt-producer-latest
    pullPolicy: IfNotPresent
  env:
    MQTT_BROKER: "tcp://traffic-system-mosquitto.traffic-system.svc.cluster.local:1883"
    MQTT_TOPIC: "traffic/data"
    FETCH_INTERVAL: 3