Version: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "kafka-poc-solar-system.labels" . | nindent 4 }}
spec:
  rules:
  {{- if and .Values.ingress .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{- else }}
  - host: ""
  {{- end }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - {}
