# Override the default Helm release name
nameOverride: kafka-ui

cluster:
  name: mykafka-cluster         # Name of the Kafka cluster
  namespace: kafka              # Kubernetes namespace where the Kafka cluster is deployed
  kafkaPort: 9092               # Port used to connect to the Kafka broker

deployment:
  replicas: 1                   # Number of Kafka UI replicas
  image: provectuslabs/kafka-ui # Docker image for Kafka UI
  tag: latest                   # Image tag
  imagePullPolicy: IfNotPresent # Kubernetes image pull policy
  imagePullSecrets:            # Optional: list of image pull secrets
    - name: registry-pull-secret
  containerPort: 8080          # Port exposed by the container

service:
  enabled: true                # Whether to create a Kubernetes service
  type: "ClusterIP"            # Kubernetes service type
  port: 8080                   # Port exposed by the service
