apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      {{- if .Values.deployment.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecret }}
      {{- end }}
      containers:
        {{- with .Values.deployment }}
        - name: {{ $.Release.Name }}-ui
          image: {{ .image }}:{{ .tag }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - containerPort: {{ .containerPort }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "{{ .env.KAFKA_CLUSTER_NAME }}"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ .env.KAFKA_BROKER }}"
        {{- end }}