{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default "kafka-ui" .Values.nameOverride }}-svc
  labels:
     app: {{ default "kafka-ui" .Values.nameOverride }}
spec:
  selector:
    app: {{ default "kafka-ui" .Values.nameOverride }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end }}