# Kafka cluster metadata and configuration
cluster:
  name: mykafka-cluster
  version: 4.0.0
  metadataVersion: 4.0-IV3
  # Kafka listener types and ports
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
  # Key Kafka configuration options
  config:
    auto.create.topics.enable: false
    default.replication.factor: 1
    delete.topic.enable: true
    min.insync.replicas: 1
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1

# NodePool configuration (roles, storage, resources)
nodePool:
  name: dual-role
  replicas: 1
  roles:
    - controller
    - broker
  volumes:
    - id: 0
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      kraftMetadata: shared
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "1"

# Example topic configuration (currently commented out)
topics:
#  - name: topic-test-data
#    partitions: 2
#    replicas: 2
#    config:
#      retention.ms: 604800000
#      segment.bytes: 104857500
#      cleanup.policy: delete