mosquitto:
  enabled: true
  
solar-system:
### Kafka web consumer configuration
  kafka-web-consumer:
    replicaCount: 1
    kafkaBroker:
      name: mykafka-cluster
      namespace: kafka
    image:
      repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc
      tag: solar-consumer-latest
    #  tag: solar-kafka-web-consumer-latest
      pullPolicy: Always

# Bridge between MQTT and Kafka
  mqtt-bridge:
    replicaCount: 1
    kafkaBroker:
      name: mykafka-cluster
      namespace: kafka
    mqttBroker:
      name: system-mosquitto
      namespace: mosquitto
    image:
      repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc
      tag: latest
      pullPolicy: IfNotPresent

### mqtt-producer configuration
  mqtt-producer:
    replicaCount: 1
    mqttBroker:
      name: solar-system-mosquitto
      namespace: solar-system
    image:
      repository: harbor.puzzle.ch/pitc-cicd-private/kafka-poc
      tag: solar-mqtt-producer-latest
      pullPolicy: IfNotPresent