{{- if and .Values.topics .Values.cluster }}
{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.cluster.name }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
{{ toYaml .config | indent 4 }}
---
{{- end }}
{{- end }}